"""LangGraph agent state definition."""

from typing import Optional, TypedDict


class AgentState(TypedDict):
    """State that flows through the LangGraph state machine.

    Attributes:
        question: The user's natural-language question.
        schema_info: Cached DB schema description.
        sql_query: The SQL query generated by the LLM.
        sql_result: Raw query result (columns, rows) or ``None``.
        error: Error message from the last SQL execution, if any.
        retry_count: Number of SQL-generation retries so far.
        answer: Final natural-language answer for the user.
        viz_type: Visualization type (``table``, ``bar``, ``line``, ``metric``).
        columns: Column names from the query result.
        rows: Data rows from the query result.
    """

    question: str
    schema_info: str
    sql_query: str
    sql_result: Optional[tuple]
    error: Optional[str]
    retry_count: int
    answer: str
    viz_type: str
    columns: list[str]
    rows: list[tuple]
